import streamlit as st
import os
import json
from datetime import datetime
from dotenv import load_dotenv  # Added for .env support
from crewai import Agent, Task, Crew, Process
from langchain_google_genai import ChatGoogleGenerativeAI
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch

# ==========================================
# 1. SETUP & CONFIGURATION
# ==========================================

# Load environment variables from .env file if it exists
load_dotenv()

st.set_page_config(page_title="AI Infographic Generator", layout="wide")

# Custom CSS for that "Canvas" feel
st.markdown("""
<style>
    .stApp { background-color: #f0f2f6; }
    .info-box {
        background-color: white;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        margin-bottom: 20px;
    }
    .stat-value { font-size: 24px; font-weight: bold; color: #4F8BF9; }
    .stat-label { font-size: 14px; color: #666; }
</style>
""", unsafe_allow_html=True)

# ==========================================
# 2. PDF GENERATION ENGINE
# ==========================================

def create_infographic_pdf(data, filename="infographic.pdf"):
    """
    Generates a visual PDF using ReportLab based on the structured JSON data.
    """
    c = canvas.Canvas(filename, pagesize=A4)
    width, height = A4
    
    # --- Background Design ---
    c.setFillColor(colors.whitesmoke)
    c.rect(0, 0, width, height, fill=1)
    
    # Header Banner
    c.setFillColor(colors.cornflowerblue)
    c.rect(0, height - 1.5*inch, width, 1.5*inch, fill=1, stroke=0)
    
    # Title
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 30)
    c.drawCentredString(width/2, height - 1*inch, f"Infographic: {data.get('topic', 'Unknown Topic')}")
    
    # --- Key Stats Section ---
    y_pos = height - 2.5*inch
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(0.5*inch, y_pos, "Key Statistics")
    
    # Draw Stat Boxes
    stats = data.get('stats', [])
    box_width = 2.2*inch
    box_y = y_pos - 1.5*inch
    
    for i, stat in enumerate(stats[:3]): # Limit to 3 stats for layout
        x_pos = 0.5*inch + (i * (box_width + 0.2*inch))
        
        # Box background
        c.setFillColor(colors.white)
        c.roundRect(x_pos, box_y, box_width, 1.2*inch, 10, fill=1, stroke=0)
        
        # Number
        c.setFillColor(colors.cornflowerblue)
        c.setFont("Helvetica-Bold", 20)
        c.drawCentredString(x_pos + box_width/2, box_y + 0.7*inch, str(stat.get('value', '')))
        
        # Label
        c.setFillColor(colors.gray)
        c.setFont("Helvetica", 10)
        c.drawCentredString(x_pos + box_width/2, box_y + 0.4*inch, str(stat.get('label', '')))

    # --- Summary Section ---
    y_pos = box_y - 0.5*inch
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(0.5*inch, y_pos, "Executive Summary")
    
    y_pos -= 0.3*inch
    c.setFont("Helvetica", 11)
    text_object = c.beginText(0.5*inch, y_pos)
    text_object.setFont("Helvetica", 11)
    text_object.setLeading(14)
    
    # Simple text wrapping (very basic for MVP)
    summary_text = data.get('summary', 'No summary available.')
    words = summary_text.split()
    line = []
    for word in words:
        line.append(word)
        if len(" ".join(line)) > 80: # approx char limit
            text_object.textLine(" ".join(line))
            line = []
    text_object.textLine(" ".join(line))
    c.drawText(text_object)
    
    # --- Fun Facts / Timeline ---
    y_pos = text_object.getY() - 0.5*inch
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(0.5*inch, y_pos, "Did You Know?")
    
    y_pos -= 0.3*inch
    c.setFont("Helvetica-Oblique", 11)
    c.drawString(0.5*inch, y_pos, f"• {data.get('fun_fact', '')}")

    # Footer
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.gray)
    c.drawCentredString(width/2, 0.5*inch, f"Generated by AI Agent Crew - {datetime.now().strftime('%Y-%m-%d')}")
    
    c.save()
    return filename

# ==========================================
# 3. CREWAI BACKEND
# ==========================================

def run_crew_research(topic, api_key):
    """
    Orchestrates the CrewAI Agents to research and format data.
    """
    
    # 1. Define the LLM (Gemini)
    llm = ChatGoogleGenerativeAI(
        model="gemini-1.5-flash",
        verbose=True,
        temperature=0.5,
        google_api_key=api_key
    )

    # 2. Define Agents
    researcher = Agent(
        role='Senior Research Analyst',
        goal=f'Uncover key statistics, historical facts, and a summary about: {topic}',
        backstory="You are an expert researcher at a data visualization firm. You find precise numbers and concise summaries.",
        llm=llm,
        verbose=True,
        allow_delegation=False
    )

    designer = Agent(
        role='Information Architect',
        goal='Structure the research into a JSON format for infographic generation',
        backstory="You take raw research and organize it into stats, short summaries, and fun facts. You MUST output strict JSON.",
        llm=llm,
        verbose=True,
        allow_delegation=False
    )

    # 3. Define Tasks
    # Note: In a real app, you would add a Search Tool (like SerperDev) here.
    # For this MVP, we rely on Gemini's internal knowledge to simulate the research 
    # to avoid needing a Serper API key immediately.
    
    research_task = Task(
        description=f"""
        Research the topic '{topic}'. 
        Find:
        1. A concise executive summary (max 50 words).
        2. 3 specific numerical statistics (e.g., "Market Cap: $1T", "Year Founded: 1998").
        3. One interesting "fun fact".
        """,
        agent=researcher,
        expected_output="A text report containing summary, 3 stats, and a fun fact."
    )

    design_task = Task(
        description="""
        Take the research provided and format it into a valid JSON object.
        The JSON structure MUST be exactly like this:
        {
            "topic": "The Topic Name",
            "summary": "The summary text...",
            "stats": [
                {"label": "Label 1", "value": "Value 1"},
                {"label": "Label 2", "value": "Value 2"},
                {"label": "Label 3", "value": "Value 3"}
            ],
            "fun_fact": "The fun fact text..."
        }
        Do not include markdown formatting (like ```json), just the raw JSON string.
        """,
        agent=designer,
        expected_output="A valid JSON string.",
        context=[research_task]
    )

    # 4. Run Crew
    crew = Crew(
        agents=[researcher, designer],
        tasks=[research_task, design_task],
        verbose=True,
        process=Process.sequential
    )

    result = crew.kickoff()
    return result

# ==========================================
# 4. STREAMLIT FRONTEND
# ==========================================

def main():
    st.sidebar.title("Configuration")
    
    # Check if API key exists in environment, otherwise use empty string
    env_api_key = os.getenv("GOOGLE_API_KEY") or ""
    
    api_key = st.sidebar.text_input("Gemini API Key", value=env_api_key, type="password")
    st.sidebar.markdown("[Get Gemini Key](https://aistudio.google.com/app/apikey)")

    st.title("🎨 AI Infographic Generator")
    st.write("Turn any topic into a visual dashboard and PDF using **CrewAI** & **Gemini**.")

    topic = st.text_input("Enter a topic (e.g., 'Artificial Intelligence', 'Tesla', 'Coffee')")

    if st.button("Generate Infographic"):
        if not api_key:
            st.error("Please enter your Google Gemini API Key in the sidebar or set GOOGLE_API_KEY in .env")
        elif not topic:
            st.warning("Please enter a topic.")
        else:
            with st.spinner('🤖 AI Agents are researching and designing...'):
                try:
                    # 1. Run the Crew
                    crew_output = run_crew_research(topic, api_key)
                    
                    # 2. Clean and Parse JSON
                    # Sometimes LLMs wrap JSON in ```json blocks, we strip them
                    raw_json = str(crew_output).strip()
                    if "```json" in raw_json:
                        raw_json = raw_json.split("```json")[1].split("```")[0]
                    elif "```" in raw_json:
                        raw_json = raw_json.split("```")[1].split("```")[0]
                    
                    data = json.loads(raw_json)

                    # 3. Display "Digital Canvas" in Streamlit
                    st.success("Research Complete!")
                    
                    st.markdown(f"## 📊 {data.get('topic', topic)}")
                    
                    # Summary
                    st.markdown("### Executive Summary")
                    st.info(data.get('summary'))

                    # Stats Row
                    st.markdown("### Key Figures")
                    cols = st.columns(3)
                    stats = data.get('stats', [])
                    for i, stat in enumerate(stats):
                        if i < 3:
                            cols[i].metric(label=stat['label'], value=stat['value'])

                    # Fun Fact
                    st.markdown("### Did You Know?")
                    st.warning(data.get('fun_fact'))

                    # 4. Generate PDF
                    pdf_file = create_infographic_pdf(data)
                    
                    # 5. Download Button
                    with open(pdf_file, "rb") as f:
                        st.download_button(
                            label="📄 Download PDF Infographic",
                            data=f,
                            file_name=f"{topic}_infographic.pdf",
                            mime="application/pdf"
                        )

                except json.JSONDecodeError:
                    st.error("The AI failed to format the data correctly. Please try again.")
                    st.text("Raw Output for debugging:")
                    st.code(crew_output)
                except Exception as e:
                    st.error(f"An error occurred: {str(e)}")

if __name__ == "__main__":
    main()